name: Production Img (Docker)

env:
  DATE_STAMP: $(date +%s)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubutu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      - name: set env vars
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_DEV

      - name: build img
        run: docker build . --file Dockerfile --tag dstoffels/portfolio:latest

      - name: tag img w date-stamp
        run: docker image tag dstoffels/portfolio:latest dstoffels/portfolio:${{env.date-stamp}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push img to Docker Hub
        run: docker push --all-tags dstoffels/portfolio
